name: cmpc
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - dglteam
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - easydict=1.9
  - h5py=3.7.0
  - opencv=4.6.0
  - pip=22.3.1
  - plotly=5.9.0
  - yaml=0.2.5
  - pip:
    - matplotlib==2.2.3
    - networkx==2.5.1
    - numpy==1.21.0
    - pandas==1.3.0
    - pillow==8.3.1
    - scipy==1.7.0
    - torch==1.9.0+cu111
    - torch-geometric==1.7.2
    - torch-scatter==2.0.7
    - torch-sparse==0.6.10
    - torch-spline-conv==1.2.1
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
    - tqdm==4.61.2
